spring:
  jpa:
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.211.132:3306/mysql?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
router:
  auth:
    url: http://localhost:8888
  account:
    url: http://localhost:8081
  order:
    url: http://localhost:8083
  product:
    url: http://localhost:8082
api:
  key: secret

server:
  port: 8081
