apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deploy
spec:
  selector:
    matchLabels:
      app: account
  replicas: 1
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account
                  image: ruanxingke/account
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-http
spec:
  ports:
    - port: 8081
      targetPort: 8081
  # ClusterIP, NodePort, LoadBalancer
  type: ClusterIP
  selector:
    app: account
